In [4]:
import numpy
from sklearn import datasets, metrics
from sklearn.cluster import KMeans

iris=datasets.load_iris(); #sklearn.datasets.base.Bunch

data=iris.data   #iris.data is numpy array 
target=iris.target

model=KMeans(n_clusters=3)


model.fit(data)

prediction = model.labels_

#print(prediction)

#prediction = numpy.choose(prediction, [0,1,2]).astype(numpy.int64)

#print(prediction)

print(metrics.accuracy_score(target, prediction, normalize=True))

print(metrics.confusion_matrix(target, prediction))

0.24
[[ 0 50  0]
 [48  0  2]
 [14  0 36]]
