In [1]:
import numpy
from sklearn import neighbors, datasets, metrics

iris=datasets.load_iris(); #sklearn.datasets.base.Bunch

trainingset=iris.data[list(range(0,150,2)),:]   #iris.data is numpy array 
trainingsettarget=iris.target[list(range(0,150,2))]

testset=iris.data[list(range(1,150,2)),:]
testsettarget=iris.target[list(range(1,150,2))]

n_neighbors=3 #variable for storing number of nearest neighbors

weights='uniform' #or weights='distance'

#creating instance of a classifier
clf = neighbors.KNeighborsClassifier(n_neighbors, weights) 

#other argument is metric (default is 'minkowski'. There are many other possibilities including 'euclidean')

#Other useful argument is p which controls power of minkowski distance. Default is 2

clf.fit(trainingset, trainingsettarget)
prediction = clf.predict(testset) #predict using the learnt classifier

print("############### Predictions #################")
print(prediction)
print("#############################################")

print("Accuracy = {0}".format(metrics.accuracy_score(testsettarget, prediction, normalize=True)))

print(metrics.classification_report(testsettarget, prediction))

print(metrics.confusion_matrix(testsettarget, prediction))


############### Predictions #################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
#############################################
Accuracy = 0.96
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        25
          1       0.96      0.92      0.94        25
          2       0.92      0.96      0.94        25

avg / total       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 23  2]
 [ 0  1 24]]
