In [1]:
import numpy
from sklearn import datasets, metrics
from sklearn.neural_network import MLPClassifier

iris=datasets.load_iris(); #sklearn.datasets.base.Bunch

trainingset=iris.data[list(range(0,150,2)),:]   #iris.data is numpy array 
trainingsettarget=iris.target[list(range(0,150,2))]

#print(trainingset)
#print(trainingsettarget)

testset=iris.data[list(range(1,150,2)),:]
testsettarget=iris.target[list(range(1,150,2))]

clf = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), random_state=1, max_iter=200)#creating instance of the classifier

# activation : {'identity', 'logistic', 'tanh', 'relu'}, default 'relu'
clf.fit(trainingset, trainingsettarget);
#print(clf.get_params())
prediction = clf.predict(testset) #predict using the learnt classifier

print(prediction)
print(clf.predict_proba(testset));
print(metrics.accuracy_score(testsettarget, prediction, normalize=True))
print(metrics.classification_report(testsettarget, prediction))
print(metrics.confusion_matrix(testsettarget, prediction))


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
[[0.8361588  0.13509768 0.02874352]
 [0.83163263 0.13470196 0.03366541]
 [0.91646717 0.06758392 0.01594891]
 [0.881653   0.09697714 0.02136985]
 [0.83428434 0.13707311 0.02864255]
 [0.86460928 0.10869328 0.02669744]
 [0.88148247 0.0957679  0.02274963]
 [0.96537693 0.02854669 0.00607638]
 [0.90755527 0.07573083 0.0167139 ]
 [0.92604739 0.05987057 0.01408204]
 [0.9168352  0.06673649 0.01642831]
 [0.83300422 0.13225727 0.03473851]
 [0.79506157 0.1685465  0.03639193]
 [0.89554581 0.08663518 0.01781901]
 [0.83080669 0.13538664 0.03380668]
 [0.88453021 0.09540435 0.02006544]
 [0.96065532 0.03290638 0.0064383 ]
 [0.89752537 0.08547529 0.01699934]
 [0.83428434 0.13707311 0.02864255]
 [0.88230825 0.09713586 0.0205559 ]
 [0.70239068 0.24032702 0.0572823 ]
 [0.88025924 0.09291707 0.02682369]
 [0.8354125  0.13330284 0.03128466]
 [0.86598222 0.107

C:\Users\SHAILESH SHAH\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
