In [2]:
import numpy
from sklearn import datasets, metrics
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

iris=datasets.load_iris(); #sklearn.datasets.base.Bunch
#iris=pd.read_csv('Iris.csv')
trainingset=iris.data[list(range(0,150,2)),:]   #iris.data is numpy array 
trainingsettarget=iris.target[list(range(0,150,2))]

testset=iris.data[list(range(1,150,2)),:]
testsettarget=iris.target[list(range(1,150,2))]

clf = DecisionTreeClassifier(criterion='entropy') #creating instance of a classifier #default criterion is gini
clf.fit(trainingset, trainingsettarget)
predictions = clf.predict(testset) #predict using the learnt classifier

print("############### Predictions #################")
print(predictions)
print("#############################################")

print("Accuracy = {0}".format(metrics.accuracy_score(testsettarget, predictions, normalize=True)))

print(metrics.classification_report(testsettarget, predictions))

print(metrics.confusion_matrix(testsettarget, predictions))

############### Predictions #################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 2]
#############################################
Accuracy = 0.96
             precision    recall  f1-score   support

          0       1.00      1.00      1.00        25
          1       0.92      0.96      0.94        25
          2       0.96      0.92      0.94        25

avg / total       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]
